package com.scaler.demoproject.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;
@Getter

@Setter
@AllArgsConstructor
@NoArgsConstructor
@MappedSuperclass// when ever you are creating product class also implement BaseModel class also
public class  BaseModel implements Serializable{
    // to implement redis
    @Id // primary key
    @GeneratedValue (strategy = GenerationType.AUTO)// id generated by spring
    private Long id;
    private Date createdAt;
    private Date updatedAt;
    private boolean isDeleted;
}
